markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: OffRails - Ruby Off Rails Blog
url: http://rubyoffrails.com
description: An blog about Ruby
twitter: rubyoffrails
github: rubyoffrails
gravatar_url: http://gravatar.com/avatar/f02c32d909e1c98a04af0ec20b436b1e
